sudo: required
services:
  - docker

before_install:
  - docker build -t shritesh99/ameiim-2019 -f Dockerfile.dev .

script:
  - docker run shritesh99/ameiim-2019 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "ameiim-2019"
  env: "Ameiim2019-env"
  bucket_name: "elasticbeanstalk-us-east-1-730759799218"
  bucket_path: "ameiim-2019"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
